// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOcj-JgAaa5kGEnzi6HuClCersBrHGU4E',
    appId: '1:250209371050:web:4288b8ec4f7f0749eba1d3',
    messagingSenderId: '250209371050',
    projectId: 'similap-9de65',
    authDomain: 'similap-9de65.firebaseapp.com',
    storageBucket: 'similap-9de65.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV_bMdz0p1ujXLrPMomfY-gSniaBA1e-I',
    appId: '1:250209371050:android:eeec488dd18d144beba1d3',
    messagingSenderId: '250209371050',
    projectId: 'similap-9de65',
    storageBucket: 'similap-9de65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1G5wFtkgdG5qT4nzICPLCAoQIXgm7kWU',
    appId: '1:250209371050:ios:83c4770a4ab79732eba1d3',
    messagingSenderId: '250209371050',
    projectId: 'similap-9de65',
    storageBucket: 'similap-9de65.appspot.com',
    androidClientId: '250209371050-h3gqpr2dnq9a1krrltiqn5oeesv8ijbc.apps.googleusercontent.com',
    iosClientId: '250209371050-0blj950slmmtfha1c69j14pcg4umha6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.citycafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1G5wFtkgdG5qT4nzICPLCAoQIXgm7kWU',
    appId: '1:250209371050:ios:83c4770a4ab79732eba1d3',
    messagingSenderId: '250209371050',
    projectId: 'similap-9de65',
    storageBucket: 'similap-9de65.appspot.com',
    androidClientId: '250209371050-h3gqpr2dnq9a1krrltiqn5oeesv8ijbc.apps.googleusercontent.com',
    iosClientId: '250209371050-0blj950slmmtfha1c69j14pcg4umha6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.citycafeApp',
  );
}
